### ISSUE TITLE
authors: fix spelling of Adam's last name from "Langly" to "Langley"

### ISSUE THREAD

**Issue by odeke-em** [aanchal4/draft-roughtime#12]
I just read through https://www.ietf.org/id/draft-roughtime-aanchal-00.txt and noticed that @agl's last name is misspelled as "Langly" instead of "Langley"
<img width="294" alt="screen shot 2019-03-06 at 9 13 37 am" src="https://user-images.githubusercontent.com/4898263/53899943-37a87a80-3ff0-11e9-9b20-8b71b0eecb9a.png">

**Comment by thpts** [comment]
This was corrected in 22883ff56.

**Comment by odeke-em** [comment]
Cool, thank you @thpts!
