### ISSUE TITLE
Comments or edits? If so, which branch?

### ISSUE THREAD

**Issue by int08h** [aanchal4/draft-roughtime#7]
Thank you for leading this effort! Getting a Roughtime RFC would be dope. 

Question about how you would like to receive comments and edits. I wasn't clear from you post on proto-roughtime: are you looking for collaborative edits, comments only, or a mixture of both? 

I see a couple of active branches with changes so it's not clear which branch(es) you would like participation on.

**Comment by aanchal4** [comment]
Hi Stuart. Thanks for stepping in to contribute. You can both add comments here or send PR off of master branch. thx.

**Comment by int08h** [comment]
Understood.
